### ISSUE TITLE
Repo à archiver ?

### ISSUE THREAD

**Issue by Seluj78** [AFPy/salt-fr#9]
cc @JulienPalard @debnet, ce n'est plus actif ?

**Comment by JulienPalard** [comment]
@arthurlogilab ?

**Comment by arthurlogilab** [comment]
J'aimerais conserver ce dépot qui sert aussi le site http://salt-fr.afpy.org/

Il n'est pas impossible qu'on réactive les meetup salt un de ces 4.

**Comment by Seluj78** [comment]
@arthurlogilab l'archivage ne veux pas dire suppression, le repo sera présent, clonable, voyable etc mais juste plus modifiable tant qu'il est archivé :)

**Comment by arthurlogilab** [comment]
ok, why not, je suis pas sûr de comprendre l’intérêt du coup.

**Comment by Seluj78** [comment]
Du cleanup :)

**Comment by JulienPalard** [comment]
Tant que le site est en ligne je ne voit pas l'intérêt d'archiver non plus, c.f. mes autres commentaires pour les anciennes PyConFr.
